# Generated by Django 2.1.2 on 2018-10-17 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confirmPassword', models.CharField(max_length=32, null=True, verbose_name='Confirm Password')),
                ('profileImage', models.ImageField(blank=True, default='', max_length=300, upload_to='vendors/profileimages/', verbose_name='Profile Avatar')),
                ('shop', models.CharField(default='', max_length=144, verbose_name='Business Name')),
                ('shopInfo', models.TextField(default='', help_text='Provide a brief decription of your business', max_length=300, verbose_name='Business Description')),
                ('shopLocation', models.CharField(default='', max_length=200, verbose_name='Business Location')),
                ('website', models.URLField(blank=True, help_text='Begin with  "http://" or "https://" .', max_length=1000, verbose_name='Website')),
                ('status', models.IntegerField(default=0)),
                ('paidAmount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
