branch-defaults:
  default:
    environment: shopCraft-dev
    group_suffix: null
global:
  application_name: shopCraft
  branch: null
  default_ec2_keyname: django-key
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
