# Generated by Django 2.1.2 on 2018-10-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=250, null=True, unique=True, verbose_name='Product Category')),
                ('categoryImage', models.ImageField(blank=True, default='', max_length=300, upload_to='categories/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='Product Name')),
                ('description', models.TextField(default='', verbose_name='Product Description')),
                ('image_one', models.ImageField(help_text='Choose an image for your product', null=True, upload_to=products.models.product_picture_directory, verbose_name='First Image')),
                ('image_two', models.ImageField(null=True, upload_to=products.models.product_picture_directory, verbose_name='Second Image')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to=products.models.product_picture_directory, verbose_name='Third Image')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
                ('deliveryInfo', models.TextField(blank=True, default='', verbose_name='Delivery Information')),
                ('slug', models.SlugField(unique=True)),
                ('prod_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Product Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Product SubCategory')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='Product SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
